# Generated by Django 4.2.1 on 2023-05-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_new_alter_email_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='new',
        ),
    ]
