# Generated by Django 4.2.1 on 2023-05-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_merge_0002_alter_email_email_0004_email_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='new',
        ),
    ]
